---
name: "run script"
on:
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run script
        run: |
          echo ${{ env.DEFAULT_BRANCH }}
          echo ${{ github.ref }}
          echo ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
          echo ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
